### PR TITLE
Sort order of hashes and ciphers

### PR DESCRIPTION
**Pull request by stephdl**
The weaker crypto is at the end of the dropdown, I would like to get it at the top

https://github.com/NethServer/dev/issues/5507

### CODE REVIEW

**Review by gsanchietti — CHANGES_REQUESTED** [review]
While I agree on changing the order of ciphers (which is almost cosmetic), there is no need to add the "(weak to strong)" label.

Users who need to change the selected cipher are doing it to create tunnels with other devices, such as routers which usually support only a limited list of ciphers.

**Comment by stephdl** [comment]
@gsanchietti  no problem to go back but with @DavidePrincipi we shared each other on the order we understand, does it is the same for everybody ?

weak to strong  is top to bottom list or bottom to top list

**Comment by gsanchietti** [comment]
No problem for the order, I'd just avoid changes to the label.

**Comment by stephdl** [comment]
translation reverted as requested :)

**Pull request merged**
